# Site settings
name: Matthew Everitt Design
title: Matthew Everitt Design
email: everit.matt@me.com
description: "Matthew Everitt Design"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: none
highlighter: pygments